Track and Set Coordinates of Canvas Objects after they have been dragged
TomGrzl/RavensPerch pull request #23
Opened 2021-03-19 16:20 UTC by TomGrzl

Added event handlers to update object coordinates in the corresponding state via id after they have been dragged

2021-03-19 21:39 UTC, jamarob requested changes
Coolio 😎 ! Easy to review!

Take a look at your onDragEnd functions, that unnecessary object creation should be changed. 

The Konva component is getting really big, I think there is some potential for refactoring.

2021-03-19 21:39 UTC, jamarob commented on frontend/src/App.js
>                  <Switch>
`Router` should go into `index.js`, this allows you to configure different routers for testing. `GlobalStyle.js` can go there too, but that's more a matter of taste.

2021-03-19 21:39 UTC, jamarob commented on frontend/src/pages/Konva.js
> +    const [circleId, setCircleId] = useState(1)
This states and the following functions just scream to be refactored into a custom hook :) https://reactjs.org/docs/hooks-custom.html (-> extra ticket, fine for now)

2021-03-19 21:39 UTC, jamarob commented on frontend/src/pages/Konva.js
> +    const handleDragStart = (e) => {
This function does nothing except logging, maybe remove it?

2021-03-19 21:39 UTC, jamarob commented on frontend/src/pages/Konva.js
> +        console.log(
console.log is super helpful during debugging, but I prefer to not leave it in the code, it has a tendency to litter up the code base and the console.

2021-03-19 21:39 UTC, jamarob commented on frontend/src/pages/Konva.js
> +                        />))}
```suggestion
                        <Rect
                            {...rect}
                            key={rect.id}
                            draggable
                            isDragging={false}
                            onDragStart={handleDragStart}
                            onDragEnd={setRectCoordinatesOnDragEnd}
                        />))}
```
spread operator is your friend ;)

2021-03-19 21:39 UTC, jamarob commented on frontend/src/pages/Konva.js
> +            'ID: ' + id + '  ' +
Backtick strings read much nicer imho

2021-03-19 21:39 UTC, jamarob commented on frontend/src/pages/Konva.js
> +                    return {...rect}
Simply return `rect`? I think there is no need to create a new object, especially if you do this on every drag end for every rect (and circle)

2021-03-19 21:39 UTC, jamarob commented on frontend/src/pages/Konva.js
> +            <button onClick={logCircles}>Log Circles</button>
Nice for experimenting.. but I don't think seeing logs is part of your user story ;)

2021-03-22 10:34 UTC, TomGrzl commented
Thanks for the feedback, it will be applied with the next pull request :)

2021-03-22 10:34 UTC, merged